allowed:
- apache-2.0
- bsd-2-clause
- bsd-3-clause
- isc
- mit
- cc0-1.0
- unlicense

cache_path: .licenses.ignored

reviewed:
  npm:
  - atob-lite
  - btoa-lite
  - lodash.get
  - lodash.set
  - lodash.uniq
  - universal-agent-2.1.0
  - universal-agent-4.0.0
