name: "Test"
on: push

jobs:
  npm_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm install
    - uses: jonabc/setup-licensed@v1
      with:
        version: '2.x'
    - run: npm run test

  licensed_ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - run: npm install --production
    - uses: jonabc/setup-licensed@v1
      with:
        version: '2.x'
    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
