name: "Test"
on: pull_request

jobs:
  npm_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10.x, 12.x, 14.x, 16.x ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: npm 
        node-version: ${{ matrix.node }}

    - run: npm install
    - uses: jonabc/setup-licensed@v1
      with:
        version: '2.x'
    - run: npm run test
