name: "Run licensed in test"
on: pull_request

jobs:
  licensed_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12.x, 14.x, 16.x ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: ${{ matrix.node }}

    - run: npm install --production --ignore-scripts
    - uses: jonabc/setup-licensed@v1
      with:
        version: '3.x'
    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: push
