name: "Run licensed in test"
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  licensed_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 10.x, 12.x ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - run: npm install --production
    - uses: jonabc/setup-licensed@v1
      with:
        version: '2.x'
    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: push
